services:
  webrtc-app:
    build: .
    network_mode: "host"
    environment:
      - ALLOWED_ORIGINS=*
      - TURN_URLS=turn:155.212.168.250:3478?transport=udp,turn:155.212.168.250:3478?transport=tcp
      - TURN_USERNAME=test
      - TURN_CREDENTIAL=secret
      - STUN_URLS=stun:stun.l.google.com:19302
      - ICE_TRANSPORT_POLICY=all
    # ports:
      # - "443:8000"   # HTTPS port (not 8080)
    volumes:
      - ./certs:/app/certs:ro          # Mount certs
      - ./static/index.html:/app/static/index.html
      - ./static/client.js:/app/static/client.js
      - ./demo-instruct.wav:/app/demo-instruct.wav
    restart: unless-stopped
  coturn:
    image: coturn/coturn:latest
    container_name: coturn-tcp-only
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf
      - ./logs:/var/log
    command: ["turnserver", "-c", "/etc/turnserver.conf"]
    restart: unless-stopped
